import { DSLNode, ComponentMapping } from "../types";
import componentMap from "../../component-map.json";

const mappings: ComponentMapping[] = componentMap.mappings;

function styleToCSS(style: Record<string, string> | undefined): string {
  if (!style) return "";
  return Object.entries(style)
    .map(([key, value]) => {
      const cssKey = key.replace(/_/g, "-");
      return `${cssKey}: ${value}`;
    })
    .join("; ");
}

function styleToBinding(style: Record<string, string> | undefined): string {
  if (!style) return "";
  const parts = Object.entries(style).map(([key, value]) => {
    const cssKey = key.replace(/_/g, "-");
    return `${cssKey}: '${value}'`;
  });
  return `style="{ ${parts.join("; ")} }"`;
}

function mapNodeToVue(node: DSLNode, indent: number): string {
  const mapping = mappings.find((m) => m.dsl_type === node.type);
  if (!mapping) {
    return `${"  ".repeat(indent)}<!-- Unknown DSL type: ${node.type} -->`;
  }

  const pad = "  ".repeat(indent);
  const props = node.props || {};

  switch (node.type) {
    case "text": {
      const content = (props.content as string) || "";
      const styleAttr = props.style ? ` :style="${JSON.stringify(styleToCSS(props.style as Record<string, string>))}"` : "";
      return `${pad}<text${styleAttr}>${content}</text>`;
    }

    case "button": {
      const text = (props.text as string) || "";
      const theme = (props.theme as string) ? ` theme="${props.theme}"` : "";
      const variant = (props.variant as string) ? ` variant="${props.variant}"` : "";
      const size = (props.size as string) ? ` size="${props.size}"` : "";
      const block = props.block ? " block" : "";
      const clickAttr = props.onTap ? ` @click="${props.onTap}"` : "";
      return `${pad}<t-button${theme}${variant}${size}${block}${clickAttr}>${text}</t-button>`;
    }

    case "image": {
      const src = (props.src as string) || "";
      const mode = (props.mode as string) || "aspectFit";
      const shape = (props.shape as string) ? ` shape="${props.shape}"` : "";
      return `${pad}<t-image src="${src}" mode="${mode}"${shape} />`;
    }

    case "swiper": {
      const images = Array.isArray(props.images) ? props.images : [];
      const autoplay = props.autoplay ? " :autoplay="true" : "";
      const nav = (props.navigation as string) ? ` navigation="${props.navigation}"` : " navigation="dots"";
      let result = `${pad}<t-swiper :list="${JSON.stringify(images)}"${autoplay}${nav} />`;
      return result;
    }

    case "input": {
      const placeholder = (props.placeholder as string) || "";
      const type = (props.type as string) || "text";
      const changeAttr = props.onInput ? ` @change="${props.onInput}"` : "";
      return `${pad}<t-input type="${type}" placeholder="${placeholder}"${changeAttr} />`;
    }

    case "tag": {
      const content = (props.content as string) || "";
      const theme = (props.theme as string) ? ` theme="${props.theme}"` : "";
      const variant = (props.variant as string) ? ` variant="${props.variant}"` : "";
      return `${pad}<t-tag${theme}${variant}>${content}</t-tag>`;
    }

    case "icon": {
      const name = (props.name as string) || "";
      const size = (props.size as string) ? ` size="${props.size}"` : "";
      return `${pad}<t-icon name="${name}"${size} />`;
    }

    case "section": {
      const children = (node.children || []).map((c) => mapNodeToVue(c, indent + 1)).join("\n");
      return `${pad}<view>\n${children}\n${pad}</view>`;
    }

    case "list": {
      const dataSource = (props.data_source as string) || "listData";
      const children = (node.children || []).map((c) => mapNodeToVue(c, indent + 2)).join("\n");
      return `${pad}<t-cell-group>\n${pad}  <t-cell v-for="(item, idx) in ${dataSource}" :key="idx">\n${children}\n${pad}  </t-cell>\n${pad}</t-cell-group>`;
    }

    default: {
      return `${pad}<${mapping.component} />`;
    }
  }
}

export function generateVueTemplate(nodes: DSLNode[]): string {
  return nodes.map((n) => mapNodeToVue(n, 3)).join("\n");
}

export function generateVueSFC(pageName: string, nodes: DSLNode[]): string {
  const template = generateVueTemplate(nodes);
  return `<template>
  <view class="page">
${template}
  </view>
</template>

<script setup lang="ts">
// Page: ${pageName}
// Auto-generated by ui-dsl-generator
</script>

<style scoped>
.page {
  padding: 20rpx;
}
</style>
`;
}
